# Generated by Django 2.2.2 on 2020-05-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_blog',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create_blog',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
